project:
  type: website
  output-dir: docs

website:
  title: "Decoupling or Illusion?"
  navbar:
    left:
      - href: report/index.qmd
        text: Report

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    number-sections: true
    theme: cosmo
    code-fold: true
    code-tools: true
    css: report/style.css
    